/* This is a translation of sortie.bf, generated by bftoc.py (by Paul Kaefer)
 * It was generated on Sunday, March 20, 2022 at 12:10PM
 */

#include <stdio.h>

void main(void)
{
    int size = 30000;
    int tape[size];
    int i = 0;

    /* Clearing the tape (array) */
    for (i=0; i<size; i++)
        tape[i] = 0;

    int ptr = 0;

    tape[ptr] -= 1;
    ptr += 8;
    tape[ptr] -= 2;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 2;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 2;
        ptr += 1;
        tape[ptr] += 2;
    }
    tape[ptr] -= 2;
    ptr += 2;
    tape[ptr] -= 3;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 2;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 2;
        ptr += 1;
        tape[ptr] += 2;
    }
    tape[ptr] -= 2;
    ptr += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
    }
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 3;
        ptr += 1;
        tape[ptr] += 3;
    }
    tape[ptr] -= 3;
    ptr += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
    }
    tape[ptr] += 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 3;
        ptr += 1;
        tape[ptr] += 3;
    }
    tape[ptr] -= 3;
    ptr += 2;
    tape[ptr] += 1;
    ptr += 1;
    tape[ptr] += 11;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 3;
        ptr += 1;
        tape[ptr] += 3;
    }
    tape[ptr] -= 3;
    ptr += 5;
    tape[ptr] += 14;
    ptr += 1;
    tape[ptr] += 72;
    ptr += 1;
    tape[ptr] += 101;
    ptr += 1;
    tape[ptr] += 108;
    ptr += 1;
    tape[ptr] += 108;
    ptr += 1;
    tape[ptr] += 111;
    ptr += 1;
    tape[ptr] += 32;
    ptr += 1;
    tape[ptr] += 87;
    ptr += 1;
    tape[ptr] += 111;
    ptr += 1;
    tape[ptr] += 114;
    ptr += 1;
    tape[ptr] += 108;
    ptr += 1;
    tape[ptr] += 100;
    ptr += 1;
    tape[ptr] += 32;
    ptr += 1;
    tape[ptr] += 33;
    ptr += 1;
    tape[ptr] += 11;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 1;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 1;
        ptr -= 1;
        tape[ptr] += 1;
    }
    tape[ptr] -= 1;
    tape[ptr] += 3;
    while (tape[ptr] != 0)
    {
        tape[ptr] -= 3;
        ptr += 1;
        tape[ptr] += 3;
    }
    tape[ptr] -= 3;
    ptr += 6;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);
    ptr += 1;
    printf("%c",tape[ptr]);

}

